name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.18.x, 1.19.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install libsofthsm2
      run: sudo apt-get install -y libsofthsm2
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./... -require-libsofthsm2
    - name: Vet
      run: go vet ./...
    - name: staticcheck
      run: staticcheck ./...
